# Generated by Django 4.2.28 on 2026-02-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceAnalyticsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('compliance_status', models.CharField(blank=True, max_length=20, null=True)),
                ('estimated_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('public_holidays_in_week', models.PositiveIntegerField(default=0)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('api_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_results', to='employees.employee')),
                ('weekly_roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_results', to='roster.weeklyroster')),
            ],
            options={
                'ordering': ['employee__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='workforceanalyticsresult',
            constraint=models.UniqueConstraint(fields=('weekly_roster', 'employee'), name='unique_analytics_per_employee_per_week'),
        ),
    ]
